function opts = ApplyEvalEnvironmentToFullPowerSweep(opts, evalEnv, userAreaSide_km)
opts.tStartStr = evalEnv.tStartStr;
opts.tEndStr = evalEnv.tEndStr;
opts.stepSec = evalEnv.stepSec;
opts.beamHalfEW_deg = evalEnv.beamHalfEW_deg;
opts.beamHalfNS_deg = evalEnv.beamHalfNS_deg;
opts.geoList = evalEnv.geoList;
opts.useIdealGsoAtGs = evalEnv.useIdealGsoAtGs;
opts.gsName = evalEnv.gsName;
opts.gsLat_deg = evalEnv.gsLat_deg;
opts.gsLon_deg = evalEnv.gsLon_deg;
opts.gsAlt_km = 0;
opts.fullBeamPower_W = evalEnv.fullBeamPower_W;
opts.beamAllocatePower_W = evalEnv.fullBeamPower_W;
opts.maxBeamPower_W = evalEnv.maxBeamPower_W;
opts.params = evalEnv.params;
opts.userDemand_Mbps = evalEnv.userDemand_Mbps;
opts.useSimulatedUsers = evalEnv.useSimulatedUsers;
opts.reassignUsersEachSlot = evalEnv.reassignUsersEachSlot;
opts.userPlacementSatList = evalEnv.userPlacementSatList;
opts.numUsersPerSatellite = evalEnv.numUsersPerSat;
opts.userAreaSide_km = userAreaSide_km;
opts.userPrefix = evalEnv.userPrefix;
opts.criticalSatelliteForEpfd = evalEnv.criticalSat;
opts.satList = evalEnv.satList;
opts.satisfactionRecordSatList = evalEnv.recordSats;
opts.satisfactionSatList = evalEnv.recordSats;
end
