%% Closed-recovery candidate graph
% Recreates the bipartite graph in the reference figure.
clear; close all; clc;

% ----- Adjustable appearance -----
lineWidth = 1;
nodeSize = 64;
labelFontSize = 17;
figureSizePx = [100, 80, 500, 760];

% ----- Nodes -----
xLeft = 0.8;
xRight = 5.1;

leftY = [11.2, 7.4, 5.4, 1.7];
leftLabels = { ...
    '$b_{5,1}^{\mathrm{off}}$', ...
    '$b_{5,8}^{\mathrm{off}}$', ...
    '$b_{2,16}^{\mathrm{off}}$', ...
    '$b_{5,16}^{\mathrm{off}}$'};

rightY = [ ...
    12.45, 11.45, 10.45, 9.45, ...
     8.45,  7.45,  6.45, 5.45, ...
     4.45,  3.45, ...
     2.45,  1.45,  0.45, -0.55];
rightLabels = { ...
    '$b_{4,1}^{\mathrm{rec}}$', ...
    '$b_{6,1}^{\mathrm{rec}}$', ...
    '$b_{1,9}^{\mathrm{rec}}$', ...
    '$b_{3,9}^{\mathrm{rec}}$', ...
    '$b_{4,8}^{\mathrm{rec}}$', ...
    '$b_{6,8}^{\mathrm{rec}}$', ...
    '$b_{1,16}^{\mathrm{rec}}$', ...
    '$b_{3,16}^{\mathrm{rec}}$', ...
    '$b_{4,8}^{\mathrm{rec}}$', ...
    '$b_{6,8}^{\mathrm{rec}}$', ...
    '$b_{4,16}^{\mathrm{rec}}$', ...
    '$b_{6,16}^{\mathrm{rec}}$', ...
    '$b_{7,8}^{\mathrm{rec}}$', ...
    '$b_{9,8}^{\mathrm{rec}}$'};

% Each row is [left-node index, right-node index].
edges = [ ...
    1 1; 1 2; 1 3; 1 4; ...
    2 5; 2 6; 2 7; 2 8; ...
    3 7; 3 8; 3 9; 3 10; ...
    4 11; 4 12; 4 13; 4 14];

% ----- Draw graph -----
fig = figure( ...
    'Color', 'w', ...
    'Position', figureSizePx, ...
    'Renderer', 'painters');
ax = axes('Parent', fig);
hold(ax, 'on');

% Draw edges before nodes so the nodes remain visually on top.
for k = 1:size(edges, 1)
    iLeft = edges(k, 1);
    iRight = edges(k, 2);
    plot(ax, [xLeft, xRight], [leftY(iLeft), rightY(iRight)], ...
        'k-', 'LineWidth', lineWidth);
end

scatter(ax, repmat(xLeft, size(leftY)), leftY, nodeSize, ...
    'k', 'filled', 'MarkerEdgeColor', 'k');
scatter(ax, repmat(xRight, size(rightY)), rightY, nodeSize, ...
    'k', 'filled', 'MarkerEdgeColor', 'k');

% Mathematical labels.
for k = 1:numel(leftY)
    text(ax, xLeft - 0.27, leftY(k), leftLabels{k}, ...
        'Interpreter', 'latex', ...
        'FontSize', labelFontSize, ...
        'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'middle');
end

for k = 1:numel(rightY)
    text(ax, xRight + 0.27, rightY(k), rightLabels{k}, ...
        'Interpreter', 'latex', ...
        'FontSize', labelFontSize, ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'middle');
end

% Omitted intermediate beam relations.
text(ax, 3.15, 8.45, '$\vdots$', ...
    'Interpreter', 'latex', 'FontSize', 22, ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle');
text(ax, 3.15, 3.25, '$\vdots$', ...
    'Interpreter', 'latex', 'FontSize', 22, ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle');

axis(ax, 'off');
xlim(ax, [-0.8, 6.75]);
ylim(ax, [-1.1, 12.85]);
set(ax, 'Position', [0.04, 0.025, 0.92, 0.95]);
hold(ax, 'off');

% ----- Export -----
scriptDir = fileparts(mfilename('fullpath'));
if isempty(scriptDir)
    scriptDir = pwd;
end
outDir = fullfile(scriptDir, '..', 'Matlab_data');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

pngPath = fullfile(outDir, 'Closed_recovery_candidate_graph_matlab.png');
pdfPath = fullfile(outDir, 'Closed_recovery_candidate_graph_matlab.pdf');
exportgraphics(fig, pngPath, 'Resolution', 1200);
exportgraphics(fig, pdfPath, 'ContentType', 'vector');

fprintf('Saved PNG: %s\n', pngPath);
fprintf('Saved PDF: %s\n', pdfPath);
